create table users (
    id bigint generated by default as identity primary key ,
    username varchar not null,
    password varchar not null,
    email varchar not null unique,
    enabled boolean
);
create table role (
    id bigint generated by default as identity primary key ,
    name varchar not null
);
create table user_role (
    user_id bigint references users(id) on delete cascade,
    role_id bigint references role(id) on delete cascade,
    primary key (user_id, role_id)
);
create table product (
    id bigint generated by default as identity primary key ,
    name varchar not null,
    price decimal,
    description varchar not null,
    quantity int check (quantity >= 1)
);
create table orders (
    id bigint generated by default as identity primary key ,
    status varchar,
    created_at timestamp,
    delivered_at timestamp,
    total_sum decimal check(total_sum >= 0.1),
    user_id bigint references users(id) on delete cascade
);
create table order_item (
    id bigint generated by default as identity primary key,
    order_id bigint references orders(id) on delete cascade,
    product_id bigint references product(id) on delete cascade,
    quantity int check (quantity >= 0),
    price_at_order decimal
);

insert into role(name) values('ROLE_USER');
insert into role(name) values('ROLE_ADMIN');
insert into role(name) values('ROLE_MANAGER');